default_stages: [commit, push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: check-json
  - id: pretty-format-json
    exclude: /common/
  - id: mixed-line-ending
  - id: debug-statements
  - id: check-added-large-files
    exclude: /static/
  - id: check-xml
  - id: check-yaml
    exclude: ^deploy/kube/
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:

  - id: black
    name: Format with Black
    entry: poetry run black
    language: python
    types: [python]
    args: ["."]

  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: python
    types: [python]
    args: [-i, -r, --in-place, --remove-all-unused-imports, --remove-duplicate-keys, --remove-unused-variable, "."]

  - id: isort
    name: isort
    entry: poetry run isort
    language: python
    types: [python]
    args: ["."]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: python
    pass_filenames: false
    types: [python]
    args: [--count, "."]

  - id: yesqa
    name: Remove usless noqa
    entry: poetry run yesqa
    language: python
    types: [python]

  - id: mypy
    name: Validate types with MyPy
    entry: poetry run mypy
    language: python
    types: [python]
    pass_filenames: false
    args:
    - "."

  - id: pylintf
    name: Pylint validation
    entry: poetry run pylint
    language: python
    types: [python]
    args:
    - --disable=all
    - --ignore-paths=alembic
    - --max-line-length=240
    - --enable=unused-import,singleton-comparison,unidiomatic-typecheck,consider-using-enumerate, consider-iterating-dictionary,line-too-long,too-many-lines,trailing-whitespace,missing-final-newline, bad-whitespace,bad-continuation,wrong-import-order,ungrouped-imports,wrong-import-position,return-in-init, function-redefined,not-in-loop,return-outside-function,undefined-variable,no-staticmethod-decorator,bad-indentation, wildcard-import,unused-variable,unused-argument
    - $(git ls-files '*.py')

  - id: update-requirements-txt
    name: update-requirements-txt
    description: 'Generate requirements.txt based on poetry.lock'
    entry: poetry
    args: [export, --format, requirements.txt, --output, requirements.txt]
    language: system
    pass_filenames: false