[tool.poetry]
name = "commonKafka"
version = "0.1.0"
description = ""
authors = ["N"]

[tool.poetry.dependencies]
python = "^3.10"
kafka-python = "^2.0.2"
boto3 = "^1.24.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
